version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-instance
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60 1", "--loglevel", "warning"]

volumes:
  redis-data:
    driver: local
